#!/usr/bin/haserl  --upload-limit=32768 --shell=/bin/ash
<% echo -en "content-type: text/html\r\n\r\n" %>
<html>
<head>
  <title>Upgrading Firmware - Do not disconnect</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <META HTTP-EQUIV="refresh" CONTENT="300; URL=http://10.130.1.20/">
  <style type="text/css">
body {
    font-family: verdana,arial,helvetica,sans-serif;
    font-size: 11px;
}
p, h1, form, button{border:0; margin:0; padding:0;}  
.section {
    margin: 0 0 30px;
    margin:0 auto;
    width:800px;
    padding:14px;
        -moz-border-radius: 20px;
        -webkit-border-radius: 20px;
        -khtml-border-radius: 20px;
    border-radius: 20px;
    border:solid 2px #b7ddf2;
    background: #FDE2BB;
}
.topbar {
    width:850px;
    height:100px;
    display: inline;
}
.titletext       {
    float: right;
    text-align: right;
    padding: 5px;
}
#outer-container {
    margin: 0 auto;
}
#outer-container .panel-container {
    border: 0;
    padding: 20px;
}
#outer-container .tab {
    border: solid 1px #999;
    border-bottom: none;
}
#inner-container .panel-container {
    border: solid 1px #aaa;
}
</style>

</head>

<body>
  <div class="section">
    <div class="topbar">
      	<img src="/images/vtlogo.png" alt="Village Telco">
		<div class="titletext">	
		  <h1>VT SECN Configuration</h1>
		</div>
    </div>
    <div id="outer-container" class="tab-container" >
      <div class="panel-container">
	     	<h2> Upgrading firmware. Please wait for the timer to count down. </h2>
        <h2>Time remaining:	<span id="seconds">300</span>.</h2>
      	<script>
      	  var seconds = 300;
      	  setInterval(
        	    function(){
                    if (seconds<=0){
                      window.location = 'http://10.130.1.20/index.html';
                    } else {
                      document.getElementById('seconds').innerHTML = --seconds;
                    }
                  }, 1000
                );
      	</script>
      	<p></p>
        <p>Your Mesh Potato is now upgrading.  The full process should take no longer than 5 minutes.  
        This page will refresh after 5 minutes to the configuration web page at the default IP address <a href="http://10.130.1.20/">http://10.130.1.20</a></p>
      	<h3>Writing vmlinux...</h3>
      	<% mtd write $FORM_vmlinux vmlinux.bin.l7  %>
      	<h3>Writing root and then rebooting... wait for timer to count down.</h3>
      	<% mtd -r write $FORM_root rootfs %>
	     </div>
      </div>
	</div>


</body>
</html> 