#!/bin/sh -x
# /etc/init.d/config_secn  

# This script creates various config files based on parameters in 
# /etc/config/secn, /etc/config/network and /etc/config/wireless

# ------------------------------------------------------------------

# Set up WiFi 

# Get the params from uci config file /etc/config/secn and wireless
SSID=`uci get secn.accesspoint.ssid`
PASSPHRASE=`uci get secn.accesspoint.passphrase`
ENCRYPTION=`uci get secn.accesspoint.encryption`
AP_DISABLE=`uci get secn.accesspoint.ap_disable`
AP_ISOL=`uci get secn.accesspoint.ap_isol`
MAXASSOC=`uci get secn.accesspoint.maxassoc`
USREG_DOMAIN=`uci get secn.accesspoint.usreg_domain`
CHANNEL=`uci get wireless.radio0.channel`
MESH_ENABLE=`uci get secn.mesh.mesh_enable`

# Set to WPA-WPA2 by default                                 
ENCRYPT="mixed-psk"

if [ $ENCRYPTION = "WPA-WPA2-AES" ]; then                                   
ENCRYPT="mixed-psk+tkip+aes"
elif [ $ENCRYPTION = "WPA-WPA2" ]; then                          
ENCRYPT="mixed-psk"                                                     
elif [ $ENCRYPTION = "WPA2" ]; then                          
ENCRYPT="psk2"                                                      
elif [ $ENCRYPTION = "WPA" ]; then                                   
ENCRYPT="psk"
elif [ $ENCRYPTION = "WEP" ]; then                          
ENCRYPT="wep"                                                     
elif [ $ENCRYPTION = "NONE" ]; then                          
ENCRYPT="none"                                                      
fi

uci set wireless.ap_0.encryption=$ENCRYPT
uci set wireless.ap_0.key=$PASSPHRASE
uci set wireless.ap_0.ssid=$SSID
uci set wireless.ap_0.mode="ap"
uci set wireless.ap_0.disabled=$AP_DISABLE
uci set wireless.ap_0.maxassoc=$MAXASSOC
uci set wireless.ap_0.isolate=$AP_ISOL

# Setup AP Isolation on mesh unless it is used for WAN
WANPORT=`uci get secn.wan.wanport`
if [ $AP_ISOL = "1" ] && [ $WANPORT != "Mesh" ]; then  
	batctl ap 1
else
	batctl ap 0
fi

#----------------------------------------------
# Set up DHCP server
# Get the DHCP parameters from uci config file /etc/config/secn

DHCP_ENABLE=`uci get secn.dhcp.enable`

DHCP_AUTH_CHK=`uci get secn.dhcp.dhcp_auth`
if [ $DHCP_AUTH_CHK = "checked" ]; then
  DHCP_AUTH='1'
else
  DHCP_AUTH='0'
fi

STARTIP=`uci get secn.dhcp.startip | cut -d = -f 2 | cut -d . -f 4`
ENDIP=`uci get secn.dhcp.endip | cut -d = -f 2 | cut -d . -f 4`
LIMIT=$((ENDIP - STARTIP))

MAXLEASES=`uci get secn.dhcp.maxleases`
LEASETERM=`uci get secn.dhcp.leaseterm`
LEASETERM=$((LEASETERM / 60))'m'
DOMAIN=`uci get secn.dhcp.domain`
OPTION_DNS=`uci get secn.dhcp.dns`
OPTION_DNS2=`uci get secn.dhcp.dns2`
OPTION_SUBNET=`uci get secn.dhcp.subnet`
OPTION_ROUTER=`uci get secn.dhcp.router`

uci set dhcp.setup.dhcpleasemax=$MAXLEASES
uci set dhcp.setup.domain=$DOMAIN
uci set dhcp.setup.authoritative=$DHCP_AUTH

uci set dhcp.lan.start=$STARTIP
uci set dhcp.lan.limit=$LIMIT
uci set dhcp.lan.leasetime=$LEASETERM
uci set dhcp.lan.dhcp_option="1,$OPTION_SUBNET  3,$OPTION_ROUTER  6,$OPTION_DNS,$OPTION_DNS2"

#---------------------------------------------

#Set up WAN Port

# Get WAN settings
WANPORT=`uci get secn.wan.wanport`
WANLAN_ENABLE=`uci get secn.wan.wanlan_enable`
ETHWANMODE=`uci get secn.wan.ethwanmode`
WANIP=`uci get secn.wan.wanip`
WANGATEWAY=`uci get secn.wan.wangateway`
WANMASK=`uci get secn.wan.wanmask`
WANDNS=`uci get secn.wan.wandns`
WANSSID=`uci get secn.wan.wanssid`
WANPASS=`uci get secn.wan.wanpass`

# Set up WAN wifi encryption 
WANENCRYPTION=`uci get secn.wan.wanencr`
# Set to WPA-WPA2 by default                                 
WANENCR="mixed-psk"

if [ $WANENCRYPTION = "WPA-WPA2-AES" ]; then                                   
WANENCR="mixed-psk+tkip+aes"
elif [ $WANENCRYPTION = "WPA-WPA2" ]; then                          
WANENCR="mixed-psk"                                                     
elif [ $WANENCRYPTION = "WPA2" ]; then                          
WANENCR="psk2"                                                      
elif [ $WANENCRYPTION = "WPA" ]; then                                   
WANENCR="psk"
elif [ $WANENCRYPTION = "WEP" ]; then                          
WANENCR="wep"                                                     
elif [ $WANENCRYPTION = "NONE" ]; then                          
WANENCR="none"                                                      
fi

# Set WAN wifi config
uci set wireless.sta_0.ssid=$WANSSID
uci set wireless.sta_0.key=$WANPASS
uci set wireless.sta_0.encryption=$WANENCR

# Clear WAN settings
uci set network.wan.ifname=''
uci set network.wan.proto=''
uci set network.wan.ipaddr=''
uci set network.wan.gateway=''
uci set network.wan.netmask=''
uci set network.wan.dns=''

uci set network.wan.service=''
uci set network.wan.apn=''
uci set network.wan.username=''
uci set network.wan.password=''
uci set network.wan.pin=''
uci set network.wan.device=''
uci set wireless.sta_0.disabled='1' # Make sure wifi WAN is off.

# Check to see if eth1 port exists eg for NanoStation M
if [ `ls /proc/sys/net/ipv4/conf | grep eth1` ]; then
	ETH1_PRESENT='1'
	else
	ETH1_PRESENT='0'
	# Clear WAN port bridging
	uci set secn.wan.wanlan_enable='0'
	WANLAN_ENABLE='0'
fi

# Set up for WAN port bridged to LAN
if [ $WANLAN_ENABLE = "checked" ]; then
	uci set network.lan.ifname='eth0 eth1'
else
	uci set network.lan.ifname='eth0'
fi

# Set up for WAN disabled
if [ $WANPORT = "Disable" ]; then
	uci set wireless.ah_0.disabled='0'
	uci set wireless.sta_0.disabled='1'
fi

# Set up for Ethernet WAN
if [ $WANPORT = "Ethernet" ]; then
    uci set network.lan.gateway='255.255.255.255'
	# Clear WAN port bridging
	uci set secn.wan.wanlan_enable='0'
	# Set up for WAN port on eth 0 or eth1
	if [ $ETH1_PRESENT = '1' ]; then
		uci set network.lan.ifname='eth0'  # make eth0 LAN
		uci set network.wan.ifname='eth1'  # make eth1 WAN
	else
		uci set network.lan.ifname='eth9'  # dummy LAN
		uci set network.wan.ifname='eth0'  # make etho WAN
	fi
fi

# Set up for Mesh WAN
if [ $WANPORT = "Mesh" ]; then
 	# Set up eth1 as LAN or WAN
	if [ $ETH1_PRESENT = '1' ]; then
		if [ $WANLAN_ENABLE = "checked" ]; then
			uci set network.wan.ifname='bat0'
			uci set network.lan.ifname='eth0 eth1'
		else 
			uci set network.wan.ifname='bat0 eth1' 
			uci set network.lan.ifname='eth0'
		fi
	else 
		uci set network.wan.ifname='bat0'
		uci set network.lan.ifname='eth0'
	fi
	uci set network.lan.gateway='255.255.255.255'
	uci set network.wan.type='bridge'
fi

# Set up for WiFi WAN
if [ $WANPORT = "WiFi" ]; then
  # Set up for wlan0 WAN port
	uci set wireless.ah_0.disabled='1'
	uci set wireless.sta_0.disabled='0'
	uci set network.wan.ifname='wlan0'
	uci set network.lan.gateway='255.255.255.255'
	# Disable mesh
	uci set secn.mesh.mesh_enable='0'
	MESH_ENABLE='0'
fi

# Disable mesh if required
if [ $MESH_ENABLE = "checked" ]; then
	uci set wireless.ah_0.disabled='0'
else
	uci set wireless.ah_0.disabled='1'
fi

# Set up for DHCP or Static
if [ $ETHWANMODE = "Static" ]; then
	uci set network.wan.proto='static'
	uci set network.wan.ipaddr=$WANIP
	uci set network.wan.gateway=$WANGATEWAY
	uci set network.wan.netmask=$WANMASK
	uci set network.wan.dns=$WANDNS

else  # Set up for DHCP
	uci set network.wan.proto='dhcp'
	uci set network.wan.ipaddr=''
	uci set network.wan.gateway=''
	uci set network.wan.netmask=''
	uci set network.wan.dns=''
fi


# Make sure firewall is enabled
/etc/init.d/firewall enable  

#----------------------------------------------

# Set up web server security configuration

# Get checkbox values
AUTH=`uci get secn.http.auth`
LIMITIP=`uci get secn.http.limitip`
ENSSL=`uci get secn.http.enssl`

# Set up basic auth
if [ $AUTH = "checked" ]; then                          
  uci set uhttpd.main.config="/etc/http.conf"
else
  uci set uhttpd.main.config="/etc/http.conf.off"
fi


# Set up Restricted IP and SSL

if [ $LIMITIP != "checked" ] && [ $ENSSL != "checked" ]; then
  uci set uhttpd.main.listen_http="0.0.0.0:80"
  uci set uhttpd.main.listen_https=""
fi

if [ $LIMITIP = "checked" ] && [ $ENSSL != "checked" ]; then
  uci set uhttpd.main.listen_http="172.31.255.254:80"
  uci set uhttpd.main.listen_https=""
fi

if [ $LIMITIP != "checked" ] && [ $ENSSL = "checked" ]; then
      uci set uhttpd.main.listen_http=""                                                  
      uci set uhttpd.main.listen_https="0.0.0.0:443"
fi

if [ $LIMITIP = "checked" ] && [ $ENSSL = "checked" ]; then
    uci set uhttpd.main.listen_http=""
    uci set uhttpd.main.listen_https="172.31.255.254:443"
fi


# Save the changes 
uci commit uhttpd
uci commit dhcp
uci commit network
uci commit wireless
uci commit secn

sleep 1

# Note:Reboot for changes to be effective

#----------------------------------------------

