#!/bin/sh -x

# /etc/init.d/config_secn  

# This script creates various config files based on parameters in 
# /etc/config/secn, /etc/config/network and /etc/config/wireless

/bin/config_secn_aster.sh

/bin/config_secn_wifi.sh

/bin/config_secn_dhcp.sh

/bin/config_secn_wan.sh

/bin/config_secn_usbmodem.sh

/bin/config_secn_http.sh

# Note:Reboot for changes to be effective

#----------------------------------------------

