#!/bin/sh

# Set up Fallback IP on LAN bridge or on eth0 if LAN port is disabled.
LANPORT_DISABLE=`uci get secn.wan.lanport_disable`
if [ $LANPORT_DISABLE = "0" ]; then
	sleep 5  # Make sure bridge is up
	ifconfig br-lan:9 172.31.255.254 netmask 255.255.255.252
else
	ifconfig eth0.1 172.31.255.254 netmask 255.255.255.252
fi

# Set up WAN Port Secondary IP
WANPORT=`uci get secn.wan.wanport`
SECWANIP=`uci get secn.wan.secwanip`
if [ $WANPORT = "Mesh" ]; then
	ifconfig "br-wan:9" $SECWANIP netmask 255.255.255.0
elif [ $WANPORT = "Ethernet" ]; then
	ifconfig "eth0.2:9" $SECWANIP netmask 255.255.255.0
elif [ $WANPORT = "2.4GHz_WiFi" ]; then
	ifconfig "wlan0-2:9" $SECWANIP netmask 255.255.255.0
elif [ $WANPORT = "5.0GHz_WiFi" ]; then
	ifconfig "wlan1-2:9" $SECWANIP netmask 255.255.255.0
fi
