#!/bin/sh

# Set up network for MT300A 

	WANETH="eth0.2"  
	LANETH="eth0.1"

# Set up Fallback IP on LAN bridge or on LANETH if LAN port is disabled.
LANPORT_DISABLE=`uci get secn.wan.lanport_disable`
if [ $LANPORT_DISABLE = "0" ]; then
	sleep 5  # make sure bridge is up
	ifconfig br-lan:9 172.31.255.254 netmask 255.255.255.252
else
	uci set network.fallback.ifname=LANETH
	uci commit network
	ifconfig $LANETH 172.31.255.254 netmask 255.255.255.252
fi

# Set up WAN Port Secondary IP
WANPORT=`uci get secn.wan.wanport`
SECWANIP=`uci get secn.wan.secwanip`
if [ $WANPORT = "Mesh" ]; then
	ifconfig "br-wan:9" $SECWANIP netmask 255.255.255.0
elif [ $WANPORT = "Ethernet" ]; then
	ifconfig $WANETH":9" $SECWANIP netmask 255.255.255.0
elif [ $WANPORT = "WiFi" ]; then
	ifconfig "wlan0-2:9" $SECWANIP netmask 255.255.255.0
fi

