#!/bin/sh
# /etc/init.d/config_rachel

# Get the wanport mode
WANPORT=`uci get rachel.setup.wanport`
# Do nothing if in SECN Advanced mode
if [ $WANPORT = "SECN-Adv" ]; then
	# Re-enable LAN port
	uci set secn.wan.lanport_disable=0
	exit
fi

# Disable LAN port to prevent accidental use as WAN port
uci set secn.wan.lanport_disable='checked'

# Disable Access Point on 5GHz
uci set secn.accesspoint1.ap_disable=1

# Disable Mesh operation if not required in VT-RACHEL mode
# 2GHz
uci set secn.mesh.mesh_disable=1
# 5GHz
if [ $WANPORT = "Mesh" ]; then
	# Enable mesh operation on 5GHz
	uci set secn.mesh1.mesh_disable=0
else
	# Disable mesh operation on both radios
	uci set secn.mesh1.mesh_disable=1
fi

# Get RACHEL USB modem settings
MODEMPORT=`uci get rachel.modem.modemport`
SERVICE=`uci get rachel.modem.service`
APN=`uci get rachel.modem.apn`
DIALSTR=`uci get rachel.modem.dialstr`
VENDOR=`uci get rachel.modem.vendor`
PRODUCT=`uci get rachel.modem.product`
PIN=`uci get rachel.modem.pin`
USERNAME=`uci get rachel.modem.username`
PASSWORD=`uci get rachel.modem.password`

# Make any RACHEL changes to modem settings here, then...

# Write USB modem settings to SECN
uci set secn.modem.modemport=$MODEMPORT
uci set secn.modem.service=$SERVICE
uci set secn.modem.apn=$APN
uci set secn.modem.dialstr=$DIALSTR
uci set secn.modem.vendor=$VENDOR
uci set secn.modem.product=$PRODUCT
uci set secn.modem.pin=$PIN
uci set secn.modem.username=$USERNAME
uci set secn.modem.password=$PASSWORD

# Get RACHEL initial settings
TOTALASSOC=`uci get rachel.setup.totalassoc`  # Total wifi connections

CLASS=`uci get rachel.setup.class`
MODE=`uci get rachel.setup.mode`
TXPOWER=`uci get rachel.setup.txpower`

# Primary AP
SSIDPREFIX=`uci get rachel.setup.ssidprefix`
SSID=`uci get rachel.setup.ssid`
PASSPHRASE=`uci get rachel.setup.passphrase`
MAXASSOC=`uci get rachel.setup.maxassoc`
ENCRYPTION=`uci get rachel.setup.encryption`

# Secondary AP
SSIDPREFIX3=`uci get rachel.setup.ssidprefix3`
SSID3=`uci get rachel.setup.ssid3`
PASSPHRASE3=`uci get rachel.setup.passphrase3`
MAXASSOC3=`uci get rachel.setup.maxassoc3`
ENCRYPTION3=`uci get rachel.setup.encryption3`

# Limit CLASS value 1-99
if [ $CLASS -gt 99 ] || [ $CLASS -lt 1 ]; then
	CLASS="1"
	uci set rachel.setup.class=$CLASS
	uci commit rachel
fi

# Build IP address with CLASS as octet 3 and octet 4                          
OCTET3=$((CLASS+100))
OCTET4="254"                                                                      
OCTET12=`uci get network.lan.ipaddr | cut -d = -f 2 | cut -d . -f 1,2`                   
IP=$OCTET12"."$OCTET3"."$OCTET4                                                            

# Save IP address
uci set network.lan.ipaddr=$IP                                                            

# Setup WAN access
WANPORT=`uci get rachel.setup.wanport`

# Save IP address
uci set secn.wan.wanport=$WANPORT   # Set only if Ethernet mode

# Get the last digits of the class number
CLASSDIGIT=`echo -n $CLASS | tail -c -1`
CLASSDIGIT2=`echo -n $CLASS | tail -c -2`

# Make sure CLASSDIGIT2 two char string for BSSID
if [ $CLASSDIGIT2 -lt 10 ]; then
	CLASSDIGIT2="0"$CLASSDIGIT2
fi

# Set WiFi channel based on last digit of CLASS
if [ $CLASSDIGIT = '1' ] || [ $CLASSDIGIT = '4' ] || [ $CLASSDIGIT = '7' ]; then
	CHAN=1
elif [ $CLASSDIGIT = '2' ] || [ $CLASSDIGIT = '5' ] || [ $CLASSDIGIT = '8' ]; then
	CHAN=6
elif [ $CLASSDIGIT = '3' ] || [ $CLASSDIGIT = '6' ] || [ $CLASSDIGIT = '9' ]; then
	CHAN=11
elif [ $CLASSDIGIT = '0' ]; then
	CHAN=6
else
	CHAN=1
fi

uci set wireless.radio0.channel=$CHAN

# Set up wifi SSID
SSID=$SSIDPREFIX-$CLASS$SSID
uci set secn.accesspoint.ssid=$SSID
SSID3=$SSIDPREFIX3-$CLASS$SSID3
uci set secn.accesspoint3.ssid=$SSID3

# Save wifi password
uci set secn.accesspoint.passphrase=$PASSPHRASE
uci set secn.accesspoint3.passphrase=$PASSPHRASE3

# Save the wifi max connections
if [ "$MAXASSOC" -le "$TOTALASSOC" ]; then
	MAXASSOC3=$((TOTALASSOC-MAXASSOC)) # Calculate the balance of connections
else
	MAXASSOC=$((TOTALASSOC-5))
	MAXASSOC3=5
fi
uci set secn.accesspoint.maxassoc=$MAXASSOC
uci set secn.accesspoint3.maxassoc=$MAXASSOC3
uci set rachel.setup.maxassoc=$MAXASSOC
uci set rachel.setup.maxassoc3=$MAXASSOC3

# Set up AP Enable
AP_ENABLE=`uci get rachel.setup.ap_enable`
if [ $AP_ENABLE = "checked" ]; then
	AP_DISABLE="0"
else
	AP_DISABLE="1"
fi
uci set secn.accesspoint.ap_disable=$AP_DISABLE

AP_ENABLE3=`uci get rachel.setup.ap_enable3`
if [ $AP_ENABLE3 = "checked" ]; then
	AP_DISABLE3="0"
else
	AP_DISABLE3="1"
fi
uci set secn.accesspoint3.ap_disable=$AP_DISABLE3

# Set up encryption
uci set secn.accesspoint.encryption=$ENCRYPTION
uci set secn.accesspoint3.encryption=$ENCRYPTION3

# Set wifi tx power
uci set wireless.radio0.txpower=$TXPOWER

# Enable DHCP
uci set secn.dhcp.enable="checked"
/bin/setdhcpsubnet.sh
uci set secn.dhcp.leaseterm="14400"
uci set secn.dhcp.startip=$OCTET12"."$OCTET3".100"
uci set secn.dhcp.endip=$OCTET12"."$OCTET3".200"
uci set secn.dhcp.maxleases="100"
uci set secn.dhcp.dhcp_auth="checked"

# Disable mesh
uci set secn.mesh.mesh_disable='1'

# Commit changes
uci commit wireless
uci commit network
uci commit secn
uci commit rachel

sleep 1

