#!/usr/bin/haserl  --upload-limit=32768 --shell=/bin/ash
<% PREAMBLE="env LD_LIBRARY_PATH=/lib:/usr/lib:/user/lib:/user/usr/lib:/lib/upgrade PATH=/bin:/sbin:/usr/bin:/usr/sbin:/user/bin:/user/sbin:/user/usr/bin:/user/usr/sbin " %>
<% upgr_cmd="$PREAMBLE /bin/store-content.sh $FORM_firmware" %>
<% echo -en "content-type: text/html\r\n\r\n" %>
<html>
<head>
	<title>Storing VT-RACHEL Content</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="refresh" content="140; URL=/index.html">
		<style type="text/css">
		@import url(/lib/configstyle.css); 
		</style>
</head>

<body>
	<div class="section">
		<div class="topbar">
		<img src="/images/vtlogo.png" alt="Village Telco">
			<div class="titletext"> 
			<h1>VT-RACHEL Content Upload</h1>
			</div>
		</div>
        
		<h2> Storing VT-RACHEL Content </h2>
		<pre>
			<% echo ' ' %>
			<% $upgr_cmd %>                                    
			<h2><a href="/rachel/index.html">Return to RACHEL Page</a></h2>
		</pre>
	</div>
</body>
</html>

