#!/bin/sh -x
# /etc/init.d/config_secn  

# Set up Asterisk
#/bin/VT-SECN_config-asterisk.sh

# Set up WiFi 
/bin/VT-SECN_config-wifi.sh

# Set up DHCP 
/bin/VT-SECN_config-dhcp.sh

# Set up WAN 
/bin/VT-SECN_config-wan-1.sh

# Set up 3G USB modem 
/bin/VT-SECN_config-3Gusb.sh

# Set up web server 
/bin/VT-SECN_config-uhttpd.sh



